name: CI-CD HotWheels Project

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências da API
        run: npm install
        working-directory: ./hotwheels-api

      - name: Instalar dependências do front-end
        run: npm install
        working-directory: ./my-app

      - name: Build do front-end
        run: npm run build
        working-directory: ./my-app

      - name: Testes E2E com Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./my-app
          start: |
            npm run start --prefix ../hotwheels-api &
            npm start
          wait-on: 'http://localhost:3000,http://localhost:5000'
          wait-on-timeout: 60

  deploy:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Instalar dependências da API
          run: npm install
          working-directory: ./hotwheels-api

        - name: Instalar dependências do front-end
          run: npm install
          working-directory: ./my-app

        - name: Build do front-end
          run: npm run build
          working-directory: ./my-app

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: sa-east-1

        - name: Deploy to S3
          run: aws s3 sync ./my-app/build s3://pucrs-hotwheels-frontend --delete
